name: GitHub Profile Trophy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trophy:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Trophy
        uses: ryo-ma/github-profile-trophy@v1
        with:
          username: SayantanS01
          output: svg
          path: ./trophy.svg
          theme: dracula
          column: -1
          row: 1

      - name: Deploy Trophy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: trophy-output
          publish_dir: .
          keep_files: false
